import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
const here=path.dirname(url.fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const app=read('src/App.tsx');
const css=['src/index.css','src/styles/base.css','src/styles/leads.css','src/styles/detail.css','src/styles/communications.css','src/styles/auxiliary.css'].map(read).join('\n');
const nav=read('src/components/NavRail.tsx');
const settings=read('src/components/SettingsModal.tsx');
const store=read('src/store.ts');
const comm=read('src/components/IOSCommPanel.tsx');
const leads=read('src/components/LeadsRail.tsx');
const detail=read('src/components/LeadDetailPanel.tsx');
const messages=read('src/components/MessagesView.tsx');
const statement=read('src/components/StatementDocument.tsx');
const viewer=read('src/components/StatementViewerOverlay.tsx');
const html=read('index.html');
const pkg=JSON.parse(read('package.json'));
const lock=JSON.parse(read('package-lock.json'));
let passed=0;
const results=[];
function check(name, ok){ if(!ok) throw new Error(`FAIL: ${name}`); passed++; results.push(`PASS ${String(passed).padStart(2,'0')} ${name}`); }
function has(text,needle){return text.includes(needle);}
function not(text,needle){return !text.includes(needle);}
const allUi=app+nav+comm+detail+leads+messages+settings+css;

check('Build version is 0.16.0', pkg.version==='0.16.0' && lock.version==='0.16.0' && lock.packages[''].version==='0.16.0');
check('Build meta identifies v16', has(html,'ReactCRM-016-20260914-DashboardPalette-React'));
check('Fixed wide mobile viewport is present', /width=1200/.test(html) && /user-scalable=yes/.test(html));
check('Inter font is loaded', /family=Inter/.test(html));
check('Inter is the global font token', has(css,"--font-family-main: 'Inter'"));
check('Controls inherit Inter globally', has(css,'button, input, textarea, select, option, a { font-family: var(--font-family-main) !important; }'));
check('Statement viewer stays sans/Inter', has(statement,'font-sans') && not(statement,'font-mono'));

check('Dashboard page background matches reference', has(css,'--bg-canvas: #F2F4F8;'));
check('Main surfaces are white', has(css,'--surface: #FFFFFF;'));
check('Soft panel color matches reference', has(css,'--soft: #F7F8FC;'));
check('Navy text/navigation color matches reference', has(css,'--navy: #1E2235;'));
check('Blue accent matches reference', has(css,'--accent-blue: #3B6FD4;'));
check('Amber accent matches reference', has(css,'--accent-amber: #C97B2A;'));
check('Green accent matches reference', has(css,'--accent-green: #1A8F7A;'));
check('Border color matches reference', has(css,'--line: #E2E6F0;') && has(css,'--line-strong: #D8DDE8;'));
check('No purple accent colors remain', !/#(?:6B4EBC|7C3AED|8B5CF6|A855F7)/i.test(allUi));
check('No pink accent colors remain', !/#(?:EC4899|F43F5E|DB2777)/i.test(allUi));
check('No red accent colors remain', !/#(?:C43B3B|DC2626|EF4444|F05C55)/i.test(allUi));
check('No red utility accent remains in statement viewer', !/text-red-/i.test(statement));
check('No gradients remain in production UI', !/linear-gradient|radial-gradient/i.test(allUi));
check('No glow effects remain in production UI', !/glow/i.test(css));

check('Topbar is always rendered', has(app,'<NavRail variant="topbar"'));
check('Sidebar is always rendered with topbar', has(app,'<NavRail variant="sidebar"'));
check('Topbar is 52px high', has(css,'--topbar-h: 52px;'));
check('Topbar is white with bottom divider', /\.forge-topbar[^\n]*border-bottom: 1px solid var\(--line\)/.test(css) && /\.forge-topbar[^\n]*background: #FFFFFF/.test(css));
check('Topbar has restrained reference shadow', /\.forge-topbar[^\n]*box-shadow: 0 1px 3px rgba\(30,34,53,.08\)/.test(css));
check('Sidebar defaults to wide', has(store,"navMode: 'sidebar-wide'"));
check('Sidebar can collapse to skinny icon bar', has(app,"setNavMode(isWide ? 'sidebar-slim' : 'sidebar-wide')") && has(css,'.forge-sidebar.slim { width: 54px; }'));
check('Sidebar can expand back to wide', has(css,'.forge-sidebar.wide { width: 220px; }'));
check('Sidebar collapse uses one button', has(nav,'className="forge-sidebar-toggle"') && has(nav,'onClick={toggleSidebar}'));
check('Obsolete topbar-only nav mode is removed', not(store,"'topbar'") && not(app,'topbar-mode') && not(app,'sidebar-mode'));
check('Topbar does not duplicate page navigation tabs', not(nav,'forge-topnav-tab'));
check('Sidebar active item uses solid blue line', /\.forge-side-tab\.active[^\n]*border-left-color: var\(--accent-blue\)/.test(css));
check('Sidebar text follows dark-nav palette', has(css,'color: #C8CCDC'));
check('Topbar/sidebar no traffic-light circles', not(nav,'forge-traffic') && not(nav,'forge-dot'));
check('Account control uses icon not initials', has(nav,'<UserRound') && not(nav,'>CB<'));
check('No avatar or initials UI remains', !/avatar/i.test(nav+leads+detail+comm) && !/initials?/i.test(nav+leads+detail+comm));
check('No circular initial CSS remains', !/border-radius:\s*50%/i.test(css));

check('No status pills were added', !/pill/i.test(nav+leads+detail+comm+css));
check('No lead status field was added', !/lead\.status|status-pill|stage-pill/i.test(nav+leads+detail+comm));
check('Middle header and content remain one continuous scroll panel', has(detail,'<div className="detail-scroll">') && has(detail,'<header className="detail-header">') && has(detail,'<div className="detail-body">'));
check('Middle header is not a separate panel surface', !/detail-header[^>]*forge-panel-surface/.test(detail));
check('Middle panel keeps one outer surface', has(app,'data-panel="lead-detail" className="forge-panel-surface"'));

check('Panel divider spacing stays exactly 12px', has(app,'const DIVIDER_WIDTH = 12;') && has(css,'min-width: 12px'));
check('Leads default width stays 400px', has(app,'const DEFAULT_LEADS_WIDTH = 400;'));
check('Communications default width stays 320px', has(app,'const DEFAULT_COMMS_WIDTH = 320;'));
check('Middle minimum width stays protected', has(app,'const MIN_DETAIL_WIDTH = 340;'));
check('Both panel widths persist independently', has(app,'saveWidth(PANEL_KEYS.leads, leadsWidth)') && has(app,'saveWidth(PANEL_KEYS.comms, commsWidth)'));
check('Both panel dividers remain draggable', (app.match(/onPointerDown=/g)||[]).length===2);
check('Double-click reset remains on both dividers', (app.match(/onDoubleClick=\{resetPanels\}/g)||[]).length===2);
check('Settings can still reset panel widths', has(settings,'onResetPanels'));
check('Panels use thin reference borders', /\.forge-panel-surface[^\n]*border: 1px solid var\(--line\)/.test(css));
check('Panels have no heavy shadow', /\.forge-panel-surface[^\n]*box-shadow: none/.test(css));

check('Navigation includes Leads', has(nav,"label: 'Leads'"));
check('Navigation includes Messages', has(nav,"label: 'Messages'"));
check('Navigation includes Email', has(nav,"label: 'Email'"));
check('Navigation includes Scanner', has(nav,"label: 'Scanner'"));
check('Navigation includes Command', has(nav,"label: 'Command'"));
check('Font size controls remain', has(settings,'<Minus size={16}/>') && has(settings,'<Plus size={16}/>'));
check('Font size changes in 0.5px steps', has(settings,'changeFont(-0.5)') && has(settings,'changeFont(0.5)'));
check('Canvas colors are limited to clean light palette', has(store,"CANVAS_COLORS = ['#F2F4F8','#F7F8FC','#FFFFFF','#EFF2FB']"));
check('Sidebar colors are limited to solid blue/navy palette', has(store,"NAV_COLORS = ['#1E2235','#26324A','#314568','#3B6FD4']"));
check('Topbar is fixed white independent from sidebar color', has(css,'background: #FFFFFF') && has(nav,'style={{ backgroundColor: navColor }}'));
check('Settings persist locally under v16 key', has(store,"forge-crm-ui-settings-v16") && has(store,'localStorage.setItem(SETTINGS_KEY'));
check('v15 settings migrate forward', has(store,"'forge-crm-ui-settings-v15'"));
check('Stored colors are restricted to approved palettes', has(store,'allowedColor(parsed.canvasColor, CANVAS_COLORS') && has(store,'allowedColor(parsed.sidebarColor, NAV_COLORS'));

check('Communications All tab exists', has(comm,"['all','messages','calls','contacts','email']") && has(comm,"activeTab === 'all'"));
check('Communications Messages tab exists', has(comm,"activeTab === 'messages'"));
check('Communications Calls tab exists', has(comm,"activeTab === 'calls'"));
check('Communications Contacts tab exists', has(comm,"activeTab === 'contacts'"));
check('Communications Email tab exists', has(comm,"activeTab === 'email'"));
check('All communications rows remain clickable', has(comm,'onClick={() => openAllItem(item)}'));
check('Message rows remain clickable', has(comm,'onClick={() => openMessageThread(item,type)}'));
check('Call rows remain clickable', has(comm,'setOpenCall(row)'));
check('Contact rows remain clickable', has(comm,'setOpenContactId(item.id)'));
check('Email rows remain clickable', has(comm,'openEmailComposer(row.lead,row.key,false)'));
check('Messages remain sorted newest first', has(comm,'newestByTime') && has(messages,'ageMinutes'));
check('Messages page opens selected thread', has(messages,'setOpenedLeadId(item.id)'));
check('Contacts search remains', has(comm,'placeholder="Search contacts"'));
check('Contacts remain alphabetically grouped', has(comm,'groupedContacts'));
check('Contact call action remains', has(comm,'title="Call"'));
check('Contact SMS action remains', has(comm,'title="SMS"'));
check('Contact WhatsApp action remains', has(comm,'title="WhatsApp"'));
check('Contact email action remains', has(comm,'title="Email"'));
check('Message composer remains inline', has(comm,'className="comm-composer"'));
check('Message send remains paper-plane icon', has(comm,'<Send size={15}/>'));
check('Email compose/reply remains inline', has(comm,'className="comm-email-compose"'));
check('Opened email keeps Reply action', has(comm,'title="Reply"'));
check('Internal dialer code stays absent', !/dialer|dtmf|keypad/i.test(app+nav+comm+css));
check('Call action never navigates CRM to tel:', not(app,'window.location.href') && not(app,'tel:'));
check('Call action supports ForgeTelephonyAdapter', has(app,'ForgeTelephonyAdapter'));
check('Call action supports Electron/mobile event handoff', has(app,"new CustomEvent('forge:call-request'"));

check('Lead list still has no avatars', not(leads,'avatar') && not(leads,'initial'));
check('Owner remains directly under company title', has(detail,'<div className="detail-contact-name">{lead.contact}</div>'));
check('Mobile keeps call/SMS/WhatsApp actions', has(detail,'onMessage={() => onOpenMessages(item.n)} whatsapp'));
check('Landline keeps call-only action', has(detail,'detail-landline-group'));
check('Statements section remains', has(detail,'Statements'));
check('Bank Account section remains', has(detail,'Bank Account'));
check('Sales Pitch section remains', has(detail,'Sales Pitch'));
check('Latest Activity remains limited to two actions', has(detail,'lead.activity.slice(0,2)'));
check('Statement overlay remains', has(viewer,'role="dialog"'));
check('Statement newer navigation remains', has(viewer,'View newer statement'));
check('Statement older navigation remains', has(viewer,'View older statement'));
check('MTD statement support remains', has(detail,'lead.mtd') && has(statement,'index === -1'));
check('Scrollbars stay hidden until hover', has(css,'scrollbar-color: transparent transparent') && has(css,':hover::-webkit-scrollbar-thumb'));
check('Scrollbar stays skinny', has(css,'width: 4px; height: 4px;'));
check('No form tags can accidentally submit/reload', !/<form\b/i.test(app+nav+comm+detail+leads+messages+settings));
check('Explicit action buttons use type=button', (app+nav+comm+detail+leads+messages+settings).includes('type="button"'));

console.log(results.join('\n'));
console.log(`TOTAL ${passed}/${passed} PASS`);
